### ISSUE TITLE
Wrong font lock used when highlighting an element containing a string with punctuation inside

### ISSUE THREAD

**Issue by codrut-fc** [yoshiki/yaml-mode#82] opened 2020-09-01 13:39 UTC
<img width="576" alt="Screen Shot 2020-09-01 at 14 32 03" src="https://user-images.githubusercontent.com/66792133/91857655-144fa180-ec60-11ea-997e-ba0030016caf.png">

This bug:
- ~happens after line 46 (for some reason).~
- triggers when dealing with an array, having a quoted string that contains numbers and a colon punctuation.
- "fixes" itself temporarily by deleting the last quote, saving, undoing, then saving again; reappears when reloading the file.
- the highlighting of the rest of the file underneath is messed up by it.

This is especially troublesome with `docker-compose.yml` file where you define port mappings like:
```yml
services:
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
```

I have no idea how to investigate/fix this myself, so I'm asking for help (please) 🙏 !

EDIT: see https://github.com/yoshiki/yaml-mode/issues/82#issuecomment-758778827 below for an investigation done by @sulami.

**Comment by eeshugerman** [comment] 2020-09-13 22:07
Glad it's not just me, I run into this a lot. I don't think line 46 is special in general, just in your example. Here's the simplest case I've managed to find:
```yaml
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
a: 'a.a'
a: 'a'

```
![image](https://user-images.githubusercontent.com/25518211/93029750-d2691880-f5da-11ea-8b0c-f62bda3fcba9.png)

(issue is present on the last line)

**Comment by codrut-fc** [comment] 2020-09-14 09:25
Thanks for providing another test case @eeshugerman, I've updated the title and description to better fit both scenarios.

**Comment by eeshugerman** [comment] 2020-11-19 22:37
It seems [this](https://github.com/yoshiki/yaml-mode/blob/master/yaml-mode.el#L281-L286) bit is to blame -- if I remove it, this issue is resolved.

Of course, removing it re-introduces the issue that it's there to solve (see the comment).

Unless someone can get to the bottom of this one, I'd argue it makes sense to remove it. IMO the case that it improves (quotes in unquoted strings) is more of an edge-case than the case that it breaks (punctuation in quoted strings), and (all else equal) less code is better than more code.

@wasamasa, thoughts?

**Comment by wasamasa** [comment] 2020-11-19 23:23
My thought on this is that I'm not going to remove code introduced by @dgutov (it's easily the most sophisticated contribution so far and he's a core Emacs developer), so battle it out with him.

**Comment by dgutov** [comment] 2020-11-20 00:16
Two things:

* The `(char-equal ?w (char-syntax (char-before (point))))` bit was there before me, I just tidied it up a bit and added a comment. It was added in https://github.com/yoshiki/yaml-mode/commit/c7c299466895d5e2b502be52bd0b323c8f82b4f3. Logically, the feature and the implementation make sense to me, but there may be some details to take care of.

* I can't reproduce this with the example in https://github.com/yoshiki/yaml-mode/issues/82#issuecomment-691732162. :-( Tried a few different Emacs versions, with `-Q`. Or with a (freely retyped) example from the first message in this report.

So... I would suggest two avenues for research: a) try checking out that older version and see whether the problems is still there, b) some print-debugging, I guess?

Also try some new version of Emacs (which ones are you seeing the problem with?) and running it with `-Q` first, to establish the full reproduction scenario.

**Comment by eeshugerman** [comment] 2020-11-20 02:56
Thanks you two for chiming in! Sure enough, I do _not_ observe the issue with `-Q`. (`-Q` is new to me btw; I'll be sure to try it next time I run into a bug.) Also I should mention that even without `-Q`, https://github.com/yoshiki/yaml-mode/issues/82#issuecomment-691732162 isn't a surefire way to reproduce the issue -- I have to mess with it<sup>1</sup> to trigger it. But no matter what I do with `-Q` it doesn't happen.

I'm using Spacemacs, so I suppose there are a lot of places this could be going awry :confused:. @codrut-fc are you using Spacemacs perchance? And/or Evil?

I'm using v27.1. IIRC I saw the issue on v26.3 as well. I'll look into installing v28/master.

--------

1. `M-x yaml-mode` after pasting (yanking) the example into the buffer, even if the buffer already had `yaml-mode` enabled, seems to reproduce the issue consistently. Ditto for pasting from `evil-emacs-state` (vs `evil-normal-state`, as I would normally). And ditto for pasting the example with one or more empty lines before it. Etcetera...

**Comment by codrut-fc** [comment] 2020-11-20 10:15
@eeshugerman yes, using Spacemacs:

```
#### System Info :computer:
- OS: darwin
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 812877409)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
```

Config file available here: https://gitlab.com/sdwolfz/dotfiles/-/blob/master/.spacemacs

**Comment by dgutov** [comment] 2020-11-20 11:07
> M-x yaml-mode after pasting (yanking) the example into the buffer

That was one of the first things I tried. ;-(

If Spacemacs is what triggers it, someone should bisect its configuration. Either of you can do it, or you can file an issue at the Spacemacs issue tracker, I guess...

**Comment by codrut-fc** [comment] 2020-11-20 11:15
I've actually looked through the Spacemacs source and I could not find anything that touches yaml-mode internals. Will try again, maybe it's not Spacemacs itself but another package installed somewhere (ansible comes to mind as it relies on yaml-mode)

**Comment by dgutov** [comment] 2020-11-20 11:21
Could be something else that's generally font-lock related, for example.

If you can comment out whole parts of the Spacemacs configuration at a time, that should make for a faster search.

**Comment by codrut-fc** [comment] 2020-11-20 11:26
@dgutov do you have any tips on "live debugging" this as the file loads? I can't seem to figure out a way to visualise and understand what's happening.

**Comment by dgutov** [comment] 2020-11-20 13:00
You could try https://github.com/Lindydancer/font-lock-studio, I suppose. Or print-debugging (meaning adding some `message` calls around the yaml-mode's font-lock code). But both require a certain level of understanding of font-lock.

I do believe you would be better served by bisecting the config, to find the smallest possible configuration where the bug can be reproduced first, either way.

**Comment by codrut-fc** [comment] 2021-01-06 11:02
I'll close this issue for now, hopefully I'll have time to investigate more into this soon...

**Comment by sulami** [comment] 2021-01-12 14:07
Picking this up because it has been annoying me for a while.

When using the example from above, I find it interesting that any editing of the buffer fixes the fontification, as does `font-lock-debug-fontify`. I can only reproduce this by pasting in the entire sample as-is, not by typing it out.

I haven't looked very deep into this just now, but I'm wondering if this could be a situation where several properties can match and the order they're applied in matters. This would mean that any incremental edit would trigger a different order of application than a loading from scratch, or something along those lines.

**Comment by dgutov** [comment] 2021-01-12 14:32
Properties? Syntax-propertize rules?

I can understand that it's annoying, but we're unlikely to make much progress without having a simple repro scenario starting with a base Emacs session.

**Comment by eeshugerman** [comment] 2021-01-12 15:08
@sulami, what's your config like? are you using spacemacs?

**Comment by sulami** [comment] 2021-01-12 15:17
Elliott Shugerman <notifications@github.com> writes:

> @sulami, what's your config like? are you using spacemacs?

Not using Spacemacs. I've got my entire config over at
https://github.com/sulami/dotfiles, including a frozen set of
dependencies, if people want to take a stab at it before I have a
chance.

**Comment by codrut-fc** [comment] 2021-01-12 15:26
OK, I was under the impression that this was a Spacemacs specific bug, but since @sulami confimed it happens outside of it then do you want me to repoen the issue?

**Comment by sulami** [comment] 2021-01-12 16:34
I think I found the culprit, my test case does not reproduce if I
disable hl-todo. Conversely, I managed to reproduce like so:

```
em -Q -l yaml-mode/yaml-mode.el -l hl-todo/hl-todo.el --eval "(global-hl-todo-mode)" /tmp/y.yml
```

This being the latest yaml-mode and the hl-todo version pinned in my
dotfiles at this point in time.

The file opened contains the snippet discussed earlier.

**Comment by sdwolfz** [comment] 2021-01-12 17:33
Pinging @tarsius, maybe he has some quick insight to share (I personally can't figure it out).

**Comment by tarsius** [comment] 2021-01-13 11:31
I don't immediately see what might be causing this.

**Comment by codrut-fc** [comment] 2021-01-13 15:32
Note: I can also confirm that excluding the `hl-todo` package in Spacemacs makes the issue go away. Now the hunt begins!

**Comment by runejuhl** [comment] 2021-01-13 17:48
I'm not using Spacemacs, but have been bugged by this same issue. Disabling `hl-todo` indeed does make the issue go away. :crossed_fingers: that you figure it out :)

**Comment by dgutov** [comment] 2021-01-13 21:14
Thanks for finding the conflict, I'll try to look into it this weekend.

**Comment by dgutov** [comment] 2021-01-17 01:26
@tarsius 

If I remove `hl-todo--syntax-table` and the associated `with-syntax-table` call, the problem doesn't occur. It seems regexp search (or most movements of point, really) can trigger `syntax-propertize-function` invocation, and when that happens while an unexpected syntax table is in effect, weird things happen.

Alternatively, adding this extra item to the `let`-binding above it seems to also do the trick:

```el
           (let ((case-fold-search nil)
                 (syntax-ppss-table (syntax-table)))
             (with-syntax-table hl-todo--syntax-table
               (funcall (if backward #'re-search-backward #'re-search-forward)
                        regexp bound t)))
```

`syntax-ppss-table` was only added in Emacs 26, though.

**Comment by tarsius** [comment] 2021-01-17 11:44
I have applied that work around. Thanks @dgutov!

**Comment by sdwolfz** [comment] 2021-01-17 14:48
I can confirm this is fixed now, Thank you very much for looking into this!

**Closed** 2021-01-18 09:52 UTC
